version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "bundle && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - '.env'
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - '.:/app'
    env_file:
      - '.env'
